---
- name: 'base dependencies'
  apt:
    update_cache: 'yes'
    cache_valid_time: 3600
    state: 'present'
    name:
      - 'autoconf'
      - 'bash-completion'
      - 'bc'
      - 'bison'
      - 'build-essential'
      - 'clang-format'
      - 'cmake'
      - 'curl'
      - 'dnsutils'
      - 'flex'
      - 'git'
      - 'htop'
      - 'ifupdown'
      - 'inetutils-traceroute'
      - 'iotop'
      - 'iproute2'
      - 'iptables'
      - 'iputils-ping'
      - 'ipvsadm'
      - 'jq'
      - 'libtool'
      - 'linux-headers-generic'
      - 'linux-tools-common'
      - 'locales'
      - 'lsof'
      - 'net-tools'
      - 'nmap'
      - 'ntp'
      - 'pkg-config'
      - 'python'
      - 'python-pip'
      - 'python3-pip'
      - 'silversearcher-ag'
      - 'socat'
      - 'strace'
      - 'sysstat'
      - 'tree'
      - 'unzip'
      - 'valgrind'
      - 'vim'

- name: 'upgrade dependencies'
  apt:
    upgrade: 'yes'

- name: 'install autojump'
  apt:
    deb: 'https://github.com/gsamokovarov/jump/releases/download/v0.22.0/jump_0.22.0_amd64.deb'

- name: 'set locales'
  locale_gen:
    name: 'en_US.UTF-8'
    state: 'present'

- name: 'set bashrc'
  template:
    src: '.bashrc'
    dest: '{{ user_home }}/.bashrc'
