---
- name: 'base dependencies'
  apt:
    update_cache: 'yes'
    cache_valid_time: 3600
    name: '{{ item }}'
    state: 'installed'
  with_items:
    - 'bc'
    - 'build-essential'
    - 'cmake'
    - 'curl'
    - 'dnsutils'
    - 'git' 
    - 'htop'
    - 'iotop'
    - 'jq' 
    - 'nmap'
    - 'python'
    - 'python-pip'
    - 'silversearcher-ag'
    - 'sysstat'
    - 'tree'
    - 'vim'

- name: 'upgrade dependencies'
  apt:
    upgrade: 'yes'

