---
- name: 'base dependencies'
  apt:
    update_cache: 'yes'
    cache_valid_time: 3600
    state: 'present'
    name:
      - 'autoconf'
      - 'bc'
      - 'bison'
      - 'build-essential'
      - 'clang-format'
      - 'cmake'
      - 'curl'
      - 'dnsutils'
      - 'flex'
      - 'git'
      - 'htop'
      - 'ifupdown'
      - 'inetutils-traceroute'
      - 'iotop'
      - 'iproute2'
      - 'iptables'
      - 'iputils-ping'
      - 'ipvsadm'
      - 'jq'
      - 'libtool'
      - 'linux-headers-generic'
      - 'linux-tools-common'
      - 'lsof'
      - 'net-tools'
      - 'nmap'
      - 'ntp'
      - 'pkg-config'
      - 'python'
      - 'python-pip'
      - 'python3-pip'
      - 'silversearcher-ag'
      - 'socat'
      - 'strace'
      - 'sysstat'
      - 'tree'
      - 'unzip'
      - 'valgrind'
      - 'vim'

- name: 'upgrade dependencies'
  apt:
    upgrade: 'yes'

- name: 'prepare base environment variables'
  template:
    src: 'set-base-env.sh'
    dest: '/etc/profile.d'
