---
- name: 'base dependencies'
  apt:
    update_cache: 'yes'
    cache_valid_time: 3600
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'autoconf'
    - 'bc'
    - 'build-essential'
    - 'clang-format'
    - 'cmake'
    - 'curl'
    - 'dnsutils'
    - 'git' 
    - 'htop'
    - 'iotop'
    - 'iproute2'
    - 'iptables'
    - 'inetutils-traceroute'
    - 'ipvsadm'
    - 'jq' 
    - 'libtool'
    - 'lsof'
    - 'net-tools'
    - 'nmap'
    - 'python'
    - 'python-pip'
    - 'silversearcher-ag'
    - 'strace'
    - 'sysstat'
    - 'tree'
    - 'valgrind'
    - 'vim'

- name: 'upgrade dependencies'
  apt:
    upgrade: 'yes'

