---
- name: 'clone bpftrace repository'
  git:
    repo: 'https://github.com/iovisor/bpftrace'
    dest: '/usr/share/bpftrace'
    force: 'yes'

- name: 'create build directory'
  file:
    path: '/usr/share/bpftrace/build'
    state: 'directory'
    mode: 0755

- name: 'prepare makefile'
  command: 'cmake -DCMAKE_BUILD_TYPE=DEBUG ..'
  args:
    chdir: '/usr/share/bpftrace/build'

- name: 'build'
  command: 'make -j3'
  args:
    chdir: '/usr/share/bpftrace/build'

- name: 'install'
  command: 'make -j3'
  args:
    chdir: '/usr/share/bpftrace/build'
