# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = 'cirocosta/mylinux'
  config.vm.box_version = '0.0.9'
  config.vm.box_check_update = false

  config.vm.hostname = 'bionic'

  config.vm.provider 'virtualbox' do |v|
    v.memory = 2048
    v.cpus = 3
  end

  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network 'private_network', ip: '192.168.10.4'

  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder './shared', '/shared'
end
