# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = 'mylinux'
  config.vm.box_check_update = false
  config.vm.hostname = 'bionic'

  config.vm.provider 'virtualbox' do |v|
    v.memory = 2048
    v.cpus = 4
  end

  config.vm.network 'private_network', ip: '192.168.10.4'
  config.vm.network "forwarded_port", guest: 25000, host: 25000
  config.vm.network "forwarded_port", guest: 25001, host: 25001

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.disksize.size = '30GB'
end
