---
go_tarball: "go1.10.4.linux-amd64.tar.gz"
go_download_location: "https://storage.googleapis.com/golang/{{ go_tarball }}"
go_tarball_checksum: "sha256:fa04efdb17a275a0c6e137f969a1c4eb878939e91e1da16060ce42f02c2ec5ec"
