---
- name: 'download the Go tarball'
  get_url:
    url: '{{ go_download_location }}'
    dest: '/usr/local/src/{{ go_tarball }}'
    checksum: '{{ go_tarball_checksum }}'

- name: 'register the current Go version (if any)'
  command: '/usr/local/go/bin/go version'
  ignore_errors: 'yes'
  register: 'go_version'
  changed_when: false

- name: 'Remove old installation of Go'
  file:
    path: '/usr/local/go'
    state: 'absent'
  when: 'go_version|failed or go_version.stdout != go_version_target'

- name: 'Extract the Go tarball if Go is not yet installed or not the desired version'
  unarchive:
    src: '/usr/local/src/{{ go_tarball }}'
    dest: '/usr/local'
    copy: 'no'
  when: 'go_version|failed or go_version.stdout != go_version_target'

- name: 'Set go env vars for all users'
  copy:
    src: 'set-env.sh'
    dest: '/etc/profile.d'
