---
# Provisions an already-running vagrant machine
# by SSHing into it.
#
# Using `hosts: default` we let Vagrant properly
# set the variables needed for the host connection
# so we don't need to care about that.

- hosts: 'kvm'
  any_errors_fatal: true
  become: true
  gather_facts: false
  roles:
    - 'bootstrap'

- hosts: 'kvm'
  become: true
  any_errors_fatal: true
  vars:
    bcc_apt_repository_distribution_release: 'artful'
    docker_apt_repository_distribution_release: 'artful'
    docker_enable_service: 'no'
  roles:
    - 'base'
    - 'clang'
    - 'go'
    - 'vim'
    - 'docker'
    - 'bcc'
