---
# Provisions an already-running vagrant machine
# by SSHing into it.
# 
# Using `hosts: default` we let Vagrant properly
# set the variables needed for the host connection
# so we don't need to care about that.

- hosts: 'default'
  any_errors_fatal: true
  become: true
  gather_facts: false
  roles:
    - 'bootstrap'

- hosts: 'default'
  become: true
  any_errors_fatal: true
  roles:
    - 'base'
    - 'go'
    - 'vim'
    - 'docker'
    - 'bcc'
