---
# Provisions an already-running vagrant machine
# by SSHing into it.
#
# Using `hosts: default` we let Vagrant properly
# set the variables needed for the host connection
# so we don't need to care about that.

- hosts: 'default'
  any_errors_fatal: true
  become: true
  gather_facts: false
  roles:
    - 'bootstrap'

- hosts: 'default'
  become: true
  any_errors_fatal: true
  tasks:
    - name: 'resize the fs to the whole disk'
      command: 'resize2fs /dev/sda1'

- hosts: 'default'
  become: true
  any_errors_fatal: true
  vars:
    docker_enable_service: 'no'
    docker_group_members: [ 'ubuntu', 'vagrant' ]
  roles:
    - 'base'
    - 'go'
    - 'vim'
    - 'docker'
    - 'bcc'
