---
- debug:
    msg: 'using user {{ user }} with home directory {{ user_home }}'

- name: 'clone configuration'
  git:
    repo: 'https://github.com/cirocosta/dot-vim'
    dest: '{{ user_home }}/.vim'
    force: 'yes'
  register: 'git_result'
  changed_when: "git_result.after|default('after') != git_result.before|default('before')"

- name: 'install ycm'
  command: './install.py --clang-completer'
  args:
    chdir: '{{ user_home }}/.vim/pack/cirocosta/start/YouCompleteMe'

- name: 'Set go env vars for all users'
  copy:
    src: 'vim-set-env.sh'
    dest: '/etc/profile.d'
