---
- debug:
    msg: 'using user {{ user }} with home directory {{ user_home }}'

- name: 'clone configuration'
  become: 'yes'
  become_user: '{{ user }}'
  git:
    repo: 'https://github.com/cirocosta/dot-vim'
    dest: '{{ user_home }}/.vim'
    force: 'yes'
  register: 'git_result'
  changed_when: "git_result.after|default('after') != git_result.before|default('before')"

- name: 'create symbolic link for vimrc'
  file:
    src: '{{ user_home }}/.vim/.vimrc'
    dest: '{{ user_home }}/.vimrc'
    owner: '{{ user }}'
    group: '{{ user }}'
    state: 'link'

- name: 'install ncm2 requirement'
  pip:
    executable: 'pip3'
    name: 'pynvim'

- name: 'install vim-go binaries'
  become: 'yes'
  become_user: '{{ user }}'
  command: 'vim -E -c GoInstallBinaries -c q'
  environment:
    HOME: '{{ user_home }}'
    PATH: '/usr/local/go/bin:{{ ansible_env.PATH }}'

- name: 'install ycm'
  become: 'yes'
  become_user: '{{ user }}'
  command: './install.py --clang-completer --rust-completer'
  args:
    chdir: '{{ user_home }}/.vim/pack/cirocosta/start/YouCompleteMe'
  environment:
    HOME: '{{ user_home }}'
    PATH: '/home/ubuntu/.cargo/bin:/usr/local/go/bin:{{ ansible_env.PATH }}'

- name: 'Set vim as default editor'
  copy:
    owner: '{{ user }}'
    group: '{{ user }}'
    src: 'vim-set-env.sh'
    dest: '/etc/profile.d'
