resource_types:
- name: semver
  type: registry-image
  source:
    repository: concourse/semver-resource


resources:
- name: repository
  type: git
  source:
    uri: https://github.com/cirocosta/mylinux
    ignore_paths: [ ./VERSION ]

- name: dot-vim
  type: git
  source:
    uri: https://github.com/cirocosta/dot-vim

- name: builder
  type: registry-image
  source:
    repository: concourse/builder

- name: bionic
  type: registry-image
  source:
    repository: ubuntu
    tag: bionic

- name: mylinux-image
  type: registry-image
  source:
    repository: cirocosta/mylinux
    username: ((docker-user))
    password: ((docker-password))

- name: version
  type: semver
  source:
    driver: git
    uri: https://((github-token))@github.com/cirocosta/mylinux
    branch: master
    file: ./VERSION
    git_user: Ciro S. Costa <cscosta@pivotal.io>


jobs:
- name: build
  serial: true
  public: true
  plan:
  - aggregate:
    - get: builder
      trigger: true
    - get: bionic
      trigger: true
    - get: repository
      trigger: true
    - get: dot-vim
      trigger: true
    - get: version
  - task: build
    privileged: true
    image: builder
    config:
      platform: linux
      params:
        REPOSITORY: cirocosta/mylinux
      inputs:
      - name: version
      - name: repository
        path: ./
      outputs:
      - name: image
      run:
        path: /bin/bash
        args: [ '-ce', 'TAG=$(cat ./version/version) build' ]
  - aggregate:
    - put: mylinux-image
      inputs: [ image ]
      params:
        image: image/image.tar
    - put: version
      params:
        bump: minor
