resources:
- name: repository
  type: git
  source:
    uri: https://github.com/cirocosta/mylinux

- name: dot-vim
  type: git
  source:
    uri: https://github.com/cirocosta/dot-vim

- name: builder
  type: registry-image
  source:
    repository: concourse/builder

- name: bionic
  type: registry-image
  source:
    repository: ubuntu
    tag: bionic

- name: mylinux-image
  type: registry-image
  source:
    repository: cirocosta/mylinux
    username: ((docker-user))
    password: ((docker-password))


jobs:
- name: build
  plan:
  - aggregate:
    - get: builder
      trigger: true
    - get: bionic
      trigger: true
    - get: repository
      trigger: true
    - get: dot-vim
      trigger: true
  - task: build
    privileged: true
    image: builder
    config:
      platform: linux
      params:
        REPOSITORY: cirocosta/mylinux
        TAG: latest
      inputs:
      - name: repository
        path: ./
      outputs:
      - name: image
      run:
        path: build
  - put: mylinux-image
    inputs: [ image ]
    params:
      image: image/image.tar
