---
- name: 'install docker dependencies'
  apt:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'apt-transport-https'
    - 'ca-certificates'

- name: 'add docker repo apt key'
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    id: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'
    state: 'present'
  register: 'add_repository_key'
  ignore_errors: true

- name: 'add docker repository'
  apt_repository:
    repo: '{{ docker_apt_repository }}'
    state: 'present'
    update_cache: 'yes'

- name: 'install docker'
  apt:
    name: 'docker-ce'
    state: 'present'

- name: 'enable docker systemd service'
  service:
    name: 'docker'
    state: 'started'
    enabled: '{{ docker_enable_service }}'

- name: 'create daemon config directory'
  file:
    path: '/etc/docker'
    state: 'directory'

- name: 'prepare default daemon configuration'
  template:
    src: 'daemon.json'
    dest: '/etc/docker/daemon.json'

- name: 'install docker-compose'
  pip:
    name: 'docker-compose'
    state: 'present'

- name: 'add users to docker group'
  user:
    name: '{{ item }}'
    groups: 'docker'
    append: 'yes'
  with_items: '{{ docker_group_members }}'
  when: 'docker_group_members is defined'
